/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as FacultiesRouteImport } from './routes/faculties'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InnovationsRouteImport } from './routes/innovations'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PatentsRouteImport } from './routes/patents'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ResearchAreasRouteImport } from './routes/research-areas'
import { Route as ResearchersRouteImport } from './routes/researchers'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ApiCommercializationRouteImport } from './routes/api/commercialization'
import { Route as ApiInnovationsRouteImport } from './routes/api/innovations'
import { Route as ApiOrganizationOptionsRouteImport } from './routes/api/organization-options'
import { Route as ApiPatentsRouteImport } from './routes/api/patents'
import { Route as ApiPublicPublicationsRouteImport } from './routes/api/public-publications'
import { Route as ApiPublicRecordRouteImport } from './routes/api/public-record'
import { Route as ApiPublicResearchRouteImport } from './routes/api/public-research'
import { Route as ApiPublicStatisticsRouteImport } from './routes/api/public-statistics'
import { Route as ApiRelatedRecordsRouteImport } from './routes/api/related-records'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as DashboardDepartmentAdminRouteImport } from './routes/dashboard.department-admin'
import { Route as DashboardFacultyAdminRouteImport } from './routes/dashboard.faculty-admin'
import { Route as DashboardIpttoOfficerRouteImport } from './routes/dashboard.iptto-officer'
import { Route as DashboardLecturerRouteImport } from './routes/dashboard.lecturer'
import { Route as DashboardSuperAdminRouteImport } from './routes/dashboard.super-admin'
import { Route as DepartmentsIndexRouteImport } from './routes/departments.index'
import { Route as DepartmentsDepartmentIdRouteImport } from './routes/departments.$departmentId'
import { Route as FacultiesIndexRouteImport } from './routes/faculties.index'
import { Route as FacultiesFacultyIdRouteImport } from './routes/faculties.$facultyId'
import { Route as InnovationsIndexRouteImport } from './routes/innovations.index'
import { Route as InnovationsInnovationIdRouteImport } from './routes/innovations.$innovationId'
import { Route as PatentsIndexRouteImport } from './routes/patents.index'
import { Route as PatentsPatentIdRouteImport } from './routes/patents.$patentId'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as ResearchRecordIdRouteImport } from './routes/research.$recordId'
import { Route as ResearchersIndexRouteImport } from './routes/researchers.index'
import { Route as ResearchersProfileIdRouteImport } from './routes/researchers.$profileId'
import { Route as SignUpIpttoRouteImport } from './routes/sign-up.iptto'
import { Route as SignUpLecturerRouteImport } from './routes/sign-up.lecturer'
import { Route as ApiAdminAccountsRouteImport } from './routes/api/admin/accounts'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAuthSignUpRouteImport } from './routes/api/auth/sign-up'
import { Route as ApiDashboardIpttoSummaryRouteImport } from './routes/api/dashboard/iptto-summary'
import { Route as ApiDashboardMeRouteImport } from './routes/api/dashboard/me'
import { Route as ApiDashboardProfileRouteImport } from './routes/api/dashboard/profile'
import { Route as ApiDashboardReportRouteImport } from './routes/api/dashboard/report'
import { Route as ApiDashboardResearchReviewRouteImport } from './routes/api/dashboard/research-review'
import { Route as ApiFilesConfirmUploadRouteImport } from './routes/api/files/confirm-upload'
import { Route as ApiFilesSignedDownloadUrlRouteImport } from './routes/api/files/signed-download-url'
import { Route as ApiFilesSignedUploadUrlRouteImport } from './routes/api/files/signed-upload-url'
import { Route as ApiInnovationsInnovationIdRouteImport } from './routes/api/innovations.$innovationId'
import { Route as ApiJobsFailedRouteImport } from './routes/api/jobs/failed'
import { Route as ApiPatentsPatentIdRouteImport } from './routes/api/patents.$patentId'
import { Route as ApiResearchApprovalTransitionsRouteImport } from './routes/api/research/approval-transitions'
import { Route as ApiResearchSubmissionsRouteImport } from './routes/api/research/submissions'
import { Route as DashboardLecturerProfileRouteImport } from './routes/dashboard.lecturer.profile'
import { Route as DashboardLecturerRequestServiceRouteImport } from './routes/dashboard.lecturer.request-service'
import { Route as DashboardLecturerSubmitRouteImport } from './routes/dashboard.lecturer.submit'
import { Route as ApiAuthStaffPasswordResetCompleteRouteImport } from './routes/api/auth/staff-password-reset/complete'
import { Route as ApiAuthStaffPasswordResetRequestRouteImport } from './routes/api/auth/staff-password-reset/request'
import { Route as ApiInnovationsInnovationIdArchiveRouteImport } from './routes/api/innovations.$innovationId.archive'
import { Route as ApiInnovationsInnovationIdPublishRouteImport } from './routes/api/innovations.$innovationId.publish'
import { Route as ApiInnovationsInnovationIdReviewRouteImport } from './routes/api/innovations.$innovationId.review'
import { Route as ApiResearchSubmissionsResearchRecordIdRouteImport } from './routes/api/research/submissions.$researchRecordId'
import { Route as DashboardLecturerEditResearchRecordIdRouteImport } from './routes/dashboard.lecturer.edit.$researchRecordId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultiesRoute = FacultiesRouteImport.update({
  id: '/faculties',
  path: '/faculties',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationsRoute = InnovationsRouteImport.update({
  id: '/innovations',
  path: '/innovations',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PatentsRoute = PatentsRouteImport.update({
  id: '/patents',
  path: '/patents',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchAreasRoute = ResearchAreasRouteImport.update({
  id: '/research-areas',
  path: '/research-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchersRoute = ResearchersRouteImport.update({
  id: '/researchers',
  path: '/researchers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommercializationRoute = ApiCommercializationRouteImport.update({
  id: '/api/commercialization',
  path: '/api/commercialization',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInnovationsRoute = ApiInnovationsRouteImport.update({
  id: '/api/innovations',
  path: '/api/innovations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationOptionsRoute = ApiOrganizationOptionsRouteImport.update({
  id: '/api/organization-options',
  path: '/api/organization-options',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatentsRoute = ApiPatentsRouteImport.update({
  id: '/api/patents',
  path: '/api/patents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPublicationsRoute = ApiPublicPublicationsRouteImport.update({
  id: '/api/public-publications',
  path: '/api/public-publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecordRoute = ApiPublicRecordRouteImport.update({
  id: '/api/public-record',
  path: '/api/public-record',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResearchRoute = ApiPublicResearchRouteImport.update({
  id: '/api/public-research',
  path: '/api/public-research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStatisticsRoute = ApiPublicStatisticsRouteImport.update({
  id: '/api/public-statistics',
  path: '/api/public-statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRelatedRecordsRoute = ApiRelatedRecordsRouteImport.update({
  id: '/api/related-records',
  path: '/api/related-records',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDepartmentAdminRoute =
  DashboardDepartmentAdminRouteImport.update({
    id: '/department-admin',
    path: '/department-admin',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFacultyAdminRoute = DashboardFacultyAdminRouteImport.update({
  id: '/faculty-admin',
  path: '/faculty-admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIpttoOfficerRoute = DashboardIpttoOfficerRouteImport.update({
  id: '/iptto-officer',
  path: '/iptto-officer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLecturerRoute = DashboardLecturerRouteImport.update({
  id: '/lecturer',
  path: '/lecturer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuperAdminRoute = DashboardSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DepartmentsRoute,
} as any)
const DepartmentsDepartmentIdRoute = DepartmentsDepartmentIdRouteImport.update({
  id: '/$departmentId',
  path: '/$departmentId',
  getParentRoute: () => DepartmentsRoute,
} as any)
const FacultiesIndexRoute = FacultiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FacultiesRoute,
} as any)
const FacultiesFacultyIdRoute = FacultiesFacultyIdRouteImport.update({
  id: '/$facultyId',
  path: '/$facultyId',
  getParentRoute: () => FacultiesRoute,
} as any)
const InnovationsIndexRoute = InnovationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InnovationsRoute,
} as any)
const InnovationsInnovationIdRoute = InnovationsInnovationIdRouteImport.update({
  id: '/$innovationId',
  path: '/$innovationId',
  getParentRoute: () => InnovationsRoute,
} as any)
const PatentsIndexRoute = PatentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatentsRoute,
} as any)
const PatentsPatentIdRoute = PatentsPatentIdRouteImport.update({
  id: '/$patentId',
  path: '/$patentId',
  getParentRoute: () => PatentsRoute,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResearchRoute,
} as any)
const ResearchRecordIdRoute = ResearchRecordIdRouteImport.update({
  id: '/$recordId',
  path: '/$recordId',
  getParentRoute: () => ResearchRoute,
} as any)
const ResearchersIndexRoute = ResearchersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResearchersRoute,
} as any)
const ResearchersProfileIdRoute = ResearchersProfileIdRouteImport.update({
  id: '/$profileId',
  path: '/$profileId',
  getParentRoute: () => ResearchersRoute,
} as any)
const SignUpIpttoRoute = SignUpIpttoRouteImport.update({
  id: '/iptto',
  path: '/iptto',
  getParentRoute: () => SignUpRoute,
} as any)
const SignUpLecturerRoute = SignUpLecturerRouteImport.update({
  id: '/lecturer',
  path: '/lecturer',
  getParentRoute: () => SignUpRoute,
} as any)
const ApiAdminAccountsRoute = ApiAdminAccountsRouteImport.update({
  id: '/api/admin/accounts',
  path: '/api/admin/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignUpRoute = ApiAuthSignUpRouteImport.update({
  id: '/api/auth/sign-up',
  path: '/api/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardIpttoSummaryRoute =
  ApiDashboardIpttoSummaryRouteImport.update({
    id: '/api/dashboard/iptto-summary',
    path: '/api/dashboard/iptto-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDashboardMeRoute = ApiDashboardMeRouteImport.update({
  id: '/api/dashboard/me',
  path: '/api/dashboard/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardProfileRoute = ApiDashboardProfileRouteImport.update({
  id: '/api/dashboard/profile',
  path: '/api/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardReportRoute = ApiDashboardReportRouteImport.update({
  id: '/api/dashboard/report',
  path: '/api/dashboard/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardResearchReviewRoute =
  ApiDashboardResearchReviewRouteImport.update({
    id: '/api/dashboard/research-review',
    path: '/api/dashboard/research-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFilesConfirmUploadRoute = ApiFilesConfirmUploadRouteImport.update({
  id: '/api/files/confirm-upload',
  path: '/api/files/confirm-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSignedDownloadUrlRoute =
  ApiFilesSignedDownloadUrlRouteImport.update({
    id: '/api/files/signed-download-url',
    path: '/api/files/signed-download-url',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFilesSignedUploadUrlRoute = ApiFilesSignedUploadUrlRouteImport.update({
  id: '/api/files/signed-upload-url',
  path: '/api/files/signed-upload-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInnovationsInnovationIdRoute =
  ApiInnovationsInnovationIdRouteImport.update({
    id: '/$innovationId',
    path: '/$innovationId',
    getParentRoute: () => ApiInnovationsRoute,
  } as any)
const ApiJobsFailedRoute = ApiJobsFailedRouteImport.update({
  id: '/api/jobs/failed',
  path: '/api/jobs/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatentsPatentIdRoute = ApiPatentsPatentIdRouteImport.update({
  id: '/$patentId',
  path: '/$patentId',
  getParentRoute: () => ApiPatentsRoute,
} as any)
const ApiResearchApprovalTransitionsRoute =
  ApiResearchApprovalTransitionsRouteImport.update({
    id: '/api/research/approval-transitions',
    path: '/api/research/approval-transitions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiResearchSubmissionsRoute = ApiResearchSubmissionsRouteImport.update({
  id: '/api/research/submissions',
  path: '/api/research/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLecturerProfileRoute =
  DashboardLecturerProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardLecturerRoute,
  } as any)
const DashboardLecturerRequestServiceRoute =
  DashboardLecturerRequestServiceRouteImport.update({
    id: '/request-service',
    path: '/request-service',
    getParentRoute: () => DashboardLecturerRoute,
  } as any)
const DashboardLecturerSubmitRoute = DashboardLecturerSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => DashboardLecturerRoute,
} as any)
const ApiAuthStaffPasswordResetCompleteRoute =
  ApiAuthStaffPasswordResetCompleteRouteImport.update({
    id: '/api/auth/staff-password-reset/complete',
    path: '/api/auth/staff-password-reset/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthStaffPasswordResetRequestRoute =
  ApiAuthStaffPasswordResetRequestRouteImport.update({
    id: '/api/auth/staff-password-reset/request',
    path: '/api/auth/staff-password-reset/request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInnovationsInnovationIdArchiveRoute =
  ApiInnovationsInnovationIdArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => ApiInnovationsInnovationIdRoute,
  } as any)
const ApiInnovationsInnovationIdPublishRoute =
  ApiInnovationsInnovationIdPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => ApiInnovationsInnovationIdRoute,
  } as any)
const ApiInnovationsInnovationIdReviewRoute =
  ApiInnovationsInnovationIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => ApiInnovationsInnovationIdRoute,
  } as any)
const ApiResearchSubmissionsResearchRecordIdRoute =
  ApiResearchSubmissionsResearchRecordIdRouteImport.update({
    id: '/$researchRecordId',
    path: '/$researchRecordId',
    getParentRoute: () => ApiResearchSubmissionsRoute,
  } as any)
const DashboardLecturerEditResearchRecordIdRoute =
  DashboardLecturerEditResearchRecordIdRouteImport.update({
    id: '/edit/$researchRecordId',
    path: '/edit/$researchRecordId',
    getParentRoute: () => DashboardLecturerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/departments': typeof DepartmentsRouteWithChildren
  '/faculties': typeof FacultiesRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/innovations': typeof InnovationsRouteWithChildren
  '/news': typeof NewsRoute
  '/patents': typeof PatentsRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRouteWithChildren
  '/research-areas': typeof ResearchAreasRoute
  '/researchers': typeof ResearchersRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRouteWithChildren
  '/api/commercialization': typeof ApiCommercializationRoute
  '/api/innovations': typeof ApiInnovationsRouteWithChildren
  '/api/organization-options': typeof ApiOrganizationOptionsRoute
  '/api/patents': typeof ApiPatentsRouteWithChildren
  '/api/public-publications': typeof ApiPublicPublicationsRoute
  '/api/public-record': typeof ApiPublicRecordRoute
  '/api/public-research': typeof ApiPublicResearchRoute
  '/api/public-statistics': typeof ApiPublicStatisticsRoute
  '/api/related-records': typeof ApiRelatedRecordsRoute
  '/api/search': typeof ApiSearchRoute
  '/dashboard/department-admin': typeof DashboardDepartmentAdminRoute
  '/dashboard/faculty-admin': typeof DashboardFacultyAdminRoute
  '/dashboard/iptto-officer': typeof DashboardIpttoOfficerRoute
  '/dashboard/lecturer': typeof DashboardLecturerRouteWithChildren
  '/dashboard/super-admin': typeof DashboardSuperAdminRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/faculties/$facultyId': typeof FacultiesFacultyIdRoute
  '/innovations/$innovationId': typeof InnovationsInnovationIdRoute
  '/patents/$patentId': typeof PatentsPatentIdRoute
  '/research/$recordId': typeof ResearchRecordIdRoute
  '/researchers/$profileId': typeof ResearchersProfileIdRoute
  '/sign-up/iptto': typeof SignUpIpttoRoute
  '/sign-up/lecturer': typeof SignUpLecturerRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/faculties/': typeof FacultiesIndexRoute
  '/innovations/': typeof InnovationsIndexRoute
  '/patents/': typeof PatentsIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/researchers/': typeof ResearchersIndexRoute
  '/api/admin/accounts': typeof ApiAdminAccountsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/api/dashboard/iptto-summary': typeof ApiDashboardIpttoSummaryRoute
  '/api/dashboard/me': typeof ApiDashboardMeRoute
  '/api/dashboard/profile': typeof ApiDashboardProfileRoute
  '/api/dashboard/report': typeof ApiDashboardReportRoute
  '/api/dashboard/research-review': typeof ApiDashboardResearchReviewRoute
  '/api/files/confirm-upload': typeof ApiFilesConfirmUploadRoute
  '/api/files/signed-download-url': typeof ApiFilesSignedDownloadUrlRoute
  '/api/files/signed-upload-url': typeof ApiFilesSignedUploadUrlRoute
  '/api/innovations/$innovationId': typeof ApiInnovationsInnovationIdRouteWithChildren
  '/api/jobs/failed': typeof ApiJobsFailedRoute
  '/api/patents/$patentId': typeof ApiPatentsPatentIdRoute
  '/api/research/approval-transitions': typeof ApiResearchApprovalTransitionsRoute
  '/api/research/submissions': typeof ApiResearchSubmissionsRouteWithChildren
  '/dashboard/lecturer/profile': typeof DashboardLecturerProfileRoute
  '/dashboard/lecturer/request-service': typeof DashboardLecturerRequestServiceRoute
  '/dashboard/lecturer/submit': typeof DashboardLecturerSubmitRoute
  '/api/auth/staff-password-reset/complete': typeof ApiAuthStaffPasswordResetCompleteRoute
  '/api/auth/staff-password-reset/request': typeof ApiAuthStaffPasswordResetRequestRoute
  '/api/innovations/$innovationId/archive': typeof ApiInnovationsInnovationIdArchiveRoute
  '/api/innovations/$innovationId/publish': typeof ApiInnovationsInnovationIdPublishRoute
  '/api/innovations/$innovationId/review': typeof ApiInnovationsInnovationIdReviewRoute
  '/api/research/submissions/$researchRecordId': typeof ApiResearchSubmissionsResearchRecordIdRoute
  '/dashboard/lecturer/edit/$researchRecordId': typeof DashboardLecturerEditResearchRecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/news': typeof NewsRoute
  '/publications': typeof PublicationsRoute
  '/reports': typeof ReportsRoute
  '/research-areas': typeof ResearchAreasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRouteWithChildren
  '/api/commercialization': typeof ApiCommercializationRoute
  '/api/innovations': typeof ApiInnovationsRouteWithChildren
  '/api/organization-options': typeof ApiOrganizationOptionsRoute
  '/api/patents': typeof ApiPatentsRouteWithChildren
  '/api/public-publications': typeof ApiPublicPublicationsRoute
  '/api/public-record': typeof ApiPublicRecordRoute
  '/api/public-research': typeof ApiPublicResearchRoute
  '/api/public-statistics': typeof ApiPublicStatisticsRoute
  '/api/related-records': typeof ApiRelatedRecordsRoute
  '/api/search': typeof ApiSearchRoute
  '/dashboard/department-admin': typeof DashboardDepartmentAdminRoute
  '/dashboard/faculty-admin': typeof DashboardFacultyAdminRoute
  '/dashboard/iptto-officer': typeof DashboardIpttoOfficerRoute
  '/dashboard/lecturer': typeof DashboardLecturerRouteWithChildren
  '/dashboard/super-admin': typeof DashboardSuperAdminRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/faculties/$facultyId': typeof FacultiesFacultyIdRoute
  '/innovations/$innovationId': typeof InnovationsInnovationIdRoute
  '/patents/$patentId': typeof PatentsPatentIdRoute
  '/research/$recordId': typeof ResearchRecordIdRoute
  '/researchers/$profileId': typeof ResearchersProfileIdRoute
  '/sign-up/iptto': typeof SignUpIpttoRoute
  '/sign-up/lecturer': typeof SignUpLecturerRoute
  '/departments': typeof DepartmentsIndexRoute
  '/faculties': typeof FacultiesIndexRoute
  '/innovations': typeof InnovationsIndexRoute
  '/patents': typeof PatentsIndexRoute
  '/research': typeof ResearchIndexRoute
  '/researchers': typeof ResearchersIndexRoute
  '/api/admin/accounts': typeof ApiAdminAccountsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/api/dashboard/iptto-summary': typeof ApiDashboardIpttoSummaryRoute
  '/api/dashboard/me': typeof ApiDashboardMeRoute
  '/api/dashboard/profile': typeof ApiDashboardProfileRoute
  '/api/dashboard/report': typeof ApiDashboardReportRoute
  '/api/dashboard/research-review': typeof ApiDashboardResearchReviewRoute
  '/api/files/confirm-upload': typeof ApiFilesConfirmUploadRoute
  '/api/files/signed-download-url': typeof ApiFilesSignedDownloadUrlRoute
  '/api/files/signed-upload-url': typeof ApiFilesSignedUploadUrlRoute
  '/api/innovations/$innovationId': typeof ApiInnovationsInnovationIdRouteWithChildren
  '/api/jobs/failed': typeof ApiJobsFailedRoute
  '/api/patents/$patentId': typeof ApiPatentsPatentIdRoute
  '/api/research/approval-transitions': typeof ApiResearchApprovalTransitionsRoute
  '/api/research/submissions': typeof ApiResearchSubmissionsRouteWithChildren
  '/dashboard/lecturer/profile': typeof DashboardLecturerProfileRoute
  '/dashboard/lecturer/request-service': typeof DashboardLecturerRequestServiceRoute
  '/dashboard/lecturer/submit': typeof DashboardLecturerSubmitRoute
  '/api/auth/staff-password-reset/complete': typeof ApiAuthStaffPasswordResetCompleteRoute
  '/api/auth/staff-password-reset/request': typeof ApiAuthStaffPasswordResetRequestRoute
  '/api/innovations/$innovationId/archive': typeof ApiInnovationsInnovationIdArchiveRoute
  '/api/innovations/$innovationId/publish': typeof ApiInnovationsInnovationIdPublishRoute
  '/api/innovations/$innovationId/review': typeof ApiInnovationsInnovationIdReviewRoute
  '/api/research/submissions/$researchRecordId': typeof ApiResearchSubmissionsResearchRecordIdRoute
  '/dashboard/lecturer/edit/$researchRecordId': typeof DashboardLecturerEditResearchRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/departments': typeof DepartmentsRouteWithChildren
  '/faculties': typeof FacultiesRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/innovations': typeof InnovationsRouteWithChildren
  '/news': typeof NewsRoute
  '/patents': typeof PatentsRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRouteWithChildren
  '/research-areas': typeof ResearchAreasRoute
  '/researchers': typeof ResearchersRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRouteWithChildren
  '/api/commercialization': typeof ApiCommercializationRoute
  '/api/innovations': typeof ApiInnovationsRouteWithChildren
  '/api/organization-options': typeof ApiOrganizationOptionsRoute
  '/api/patents': typeof ApiPatentsRouteWithChildren
  '/api/public-publications': typeof ApiPublicPublicationsRoute
  '/api/public-record': typeof ApiPublicRecordRoute
  '/api/public-research': typeof ApiPublicResearchRoute
  '/api/public-statistics': typeof ApiPublicStatisticsRoute
  '/api/related-records': typeof ApiRelatedRecordsRoute
  '/api/search': typeof ApiSearchRoute
  '/dashboard/department-admin': typeof DashboardDepartmentAdminRoute
  '/dashboard/faculty-admin': typeof DashboardFacultyAdminRoute
  '/dashboard/iptto-officer': typeof DashboardIpttoOfficerRoute
  '/dashboard/lecturer': typeof DashboardLecturerRouteWithChildren
  '/dashboard/super-admin': typeof DashboardSuperAdminRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/faculties/$facultyId': typeof FacultiesFacultyIdRoute
  '/innovations/$innovationId': typeof InnovationsInnovationIdRoute
  '/patents/$patentId': typeof PatentsPatentIdRoute
  '/research/$recordId': typeof ResearchRecordIdRoute
  '/researchers/$profileId': typeof ResearchersProfileIdRoute
  '/sign-up/iptto': typeof SignUpIpttoRoute
  '/sign-up/lecturer': typeof SignUpLecturerRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/faculties/': typeof FacultiesIndexRoute
  '/innovations/': typeof InnovationsIndexRoute
  '/patents/': typeof PatentsIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/researchers/': typeof ResearchersIndexRoute
  '/api/admin/accounts': typeof ApiAdminAccountsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/api/dashboard/iptto-summary': typeof ApiDashboardIpttoSummaryRoute
  '/api/dashboard/me': typeof ApiDashboardMeRoute
  '/api/dashboard/profile': typeof ApiDashboardProfileRoute
  '/api/dashboard/report': typeof ApiDashboardReportRoute
  '/api/dashboard/research-review': typeof ApiDashboardResearchReviewRoute
  '/api/files/confirm-upload': typeof ApiFilesConfirmUploadRoute
  '/api/files/signed-download-url': typeof ApiFilesSignedDownloadUrlRoute
  '/api/files/signed-upload-url': typeof ApiFilesSignedUploadUrlRoute
  '/api/innovations/$innovationId': typeof ApiInnovationsInnovationIdRouteWithChildren
  '/api/jobs/failed': typeof ApiJobsFailedRoute
  '/api/patents/$patentId': typeof ApiPatentsPatentIdRoute
  '/api/research/approval-transitions': typeof ApiResearchApprovalTransitionsRoute
  '/api/research/submissions': typeof ApiResearchSubmissionsRouteWithChildren
  '/dashboard/lecturer/profile': typeof DashboardLecturerProfileRoute
  '/dashboard/lecturer/request-service': typeof DashboardLecturerRequestServiceRoute
  '/dashboard/lecturer/submit': typeof DashboardLecturerSubmitRoute
  '/api/auth/staff-password-reset/complete': typeof ApiAuthStaffPasswordResetCompleteRoute
  '/api/auth/staff-password-reset/request': typeof ApiAuthStaffPasswordResetRequestRoute
  '/api/innovations/$innovationId/archive': typeof ApiInnovationsInnovationIdArchiveRoute
  '/api/innovations/$innovationId/publish': typeof ApiInnovationsInnovationIdPublishRoute
  '/api/innovations/$innovationId/review': typeof ApiInnovationsInnovationIdReviewRoute
  '/api/research/submissions/$researchRecordId': typeof ApiResearchSubmissionsResearchRecordIdRoute
  '/dashboard/lecturer/edit/$researchRecordId': typeof DashboardLecturerEditResearchRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/departments'
    | '/faculties'
    | '/faq'
    | '/forgot-password'
    | '/innovations'
    | '/news'
    | '/patents'
    | '/publications'
    | '/reports'
    | '/research'
    | '/research-areas'
    | '/researchers'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/commercialization'
    | '/api/innovations'
    | '/api/organization-options'
    | '/api/patents'
    | '/api/public-publications'
    | '/api/public-record'
    | '/api/public-research'
    | '/api/public-statistics'
    | '/api/related-records'
    | '/api/search'
    | '/dashboard/department-admin'
    | '/dashboard/faculty-admin'
    | '/dashboard/iptto-officer'
    | '/dashboard/lecturer'
    | '/dashboard/super-admin'
    | '/departments/$departmentId'
    | '/faculties/$facultyId'
    | '/innovations/$innovationId'
    | '/patents/$patentId'
    | '/research/$recordId'
    | '/researchers/$profileId'
    | '/sign-up/iptto'
    | '/sign-up/lecturer'
    | '/departments/'
    | '/faculties/'
    | '/innovations/'
    | '/patents/'
    | '/research/'
    | '/researchers/'
    | '/api/admin/accounts'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/auth/sign-up'
    | '/api/dashboard/iptto-summary'
    | '/api/dashboard/me'
    | '/api/dashboard/profile'
    | '/api/dashboard/report'
    | '/api/dashboard/research-review'
    | '/api/files/confirm-upload'
    | '/api/files/signed-download-url'
    | '/api/files/signed-upload-url'
    | '/api/innovations/$innovationId'
    | '/api/jobs/failed'
    | '/api/patents/$patentId'
    | '/api/research/approval-transitions'
    | '/api/research/submissions'
    | '/dashboard/lecturer/profile'
    | '/dashboard/lecturer/request-service'
    | '/dashboard/lecturer/submit'
    | '/api/auth/staff-password-reset/complete'
    | '/api/auth/staff-password-reset/request'
    | '/api/innovations/$innovationId/archive'
    | '/api/innovations/$innovationId/publish'
    | '/api/innovations/$innovationId/review'
    | '/api/research/submissions/$researchRecordId'
    | '/dashboard/lecturer/edit/$researchRecordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/news'
    | '/publications'
    | '/reports'
    | '/research-areas'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/commercialization'
    | '/api/innovations'
    | '/api/organization-options'
    | '/api/patents'
    | '/api/public-publications'
    | '/api/public-record'
    | '/api/public-research'
    | '/api/public-statistics'
    | '/api/related-records'
    | '/api/search'
    | '/dashboard/department-admin'
    | '/dashboard/faculty-admin'
    | '/dashboard/iptto-officer'
    | '/dashboard/lecturer'
    | '/dashboard/super-admin'
    | '/departments/$departmentId'
    | '/faculties/$facultyId'
    | '/innovations/$innovationId'
    | '/patents/$patentId'
    | '/research/$recordId'
    | '/researchers/$profileId'
    | '/sign-up/iptto'
    | '/sign-up/lecturer'
    | '/departments'
    | '/faculties'
    | '/innovations'
    | '/patents'
    | '/research'
    | '/researchers'
    | '/api/admin/accounts'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/auth/sign-up'
    | '/api/dashboard/iptto-summary'
    | '/api/dashboard/me'
    | '/api/dashboard/profile'
    | '/api/dashboard/report'
    | '/api/dashboard/research-review'
    | '/api/files/confirm-upload'
    | '/api/files/signed-download-url'
    | '/api/files/signed-upload-url'
    | '/api/innovations/$innovationId'
    | '/api/jobs/failed'
    | '/api/patents/$patentId'
    | '/api/research/approval-transitions'
    | '/api/research/submissions'
    | '/dashboard/lecturer/profile'
    | '/dashboard/lecturer/request-service'
    | '/dashboard/lecturer/submit'
    | '/api/auth/staff-password-reset/complete'
    | '/api/auth/staff-password-reset/request'
    | '/api/innovations/$innovationId/archive'
    | '/api/innovations/$innovationId/publish'
    | '/api/innovations/$innovationId/review'
    | '/api/research/submissions/$researchRecordId'
    | '/dashboard/lecturer/edit/$researchRecordId'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dashboard'
    | '/departments'
    | '/faculties'
    | '/faq'
    | '/forgot-password'
    | '/innovations'
    | '/news'
    | '/patents'
    | '/publications'
    | '/reports'
    | '/research'
    | '/research-areas'
    | '/researchers'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/commercialization'
    | '/api/innovations'
    | '/api/organization-options'
    | '/api/patents'
    | '/api/public-publications'
    | '/api/public-record'
    | '/api/public-research'
    | '/api/public-statistics'
    | '/api/related-records'
    | '/api/search'
    | '/dashboard/department-admin'
    | '/dashboard/faculty-admin'
    | '/dashboard/iptto-officer'
    | '/dashboard/lecturer'
    | '/dashboard/super-admin'
    | '/departments/$departmentId'
    | '/faculties/$facultyId'
    | '/innovations/$innovationId'
    | '/patents/$patentId'
    | '/research/$recordId'
    | '/researchers/$profileId'
    | '/sign-up/iptto'
    | '/sign-up/lecturer'
    | '/departments/'
    | '/faculties/'
    | '/innovations/'
    | '/patents/'
    | '/research/'
    | '/researchers/'
    | '/api/admin/accounts'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/auth/sign-up'
    | '/api/dashboard/iptto-summary'
    | '/api/dashboard/me'
    | '/api/dashboard/profile'
    | '/api/dashboard/report'
    | '/api/dashboard/research-review'
    | '/api/files/confirm-upload'
    | '/api/files/signed-download-url'
    | '/api/files/signed-upload-url'
    | '/api/innovations/$innovationId'
    | '/api/jobs/failed'
    | '/api/patents/$patentId'
    | '/api/research/approval-transitions'
    | '/api/research/submissions'
    | '/dashboard/lecturer/profile'
    | '/dashboard/lecturer/request-service'
    | '/dashboard/lecturer/submit'
    | '/api/auth/staff-password-reset/complete'
    | '/api/auth/staff-password-reset/request'
    | '/api/innovations/$innovationId/archive'
    | '/api/innovations/$innovationId/publish'
    | '/api/innovations/$innovationId/review'
    | '/api/research/submissions/$researchRecordId'
    | '/dashboard/lecturer/edit/$researchRecordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DepartmentsRoute: typeof DepartmentsRouteWithChildren
  FacultiesRoute: typeof FacultiesRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InnovationsRoute: typeof InnovationsRouteWithChildren
  NewsRoute: typeof NewsRoute
  PatentsRoute: typeof PatentsRouteWithChildren
  PublicationsRoute: typeof PublicationsRoute
  ReportsRoute: typeof ReportsRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  ResearchAreasRoute: typeof ResearchAreasRoute
  ResearchersRoute: typeof ResearchersRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRouteWithChildren
  ApiCommercializationRoute: typeof ApiCommercializationRoute
  ApiInnovationsRoute: typeof ApiInnovationsRouteWithChildren
  ApiOrganizationOptionsRoute: typeof ApiOrganizationOptionsRoute
  ApiPatentsRoute: typeof ApiPatentsRouteWithChildren
  ApiPublicPublicationsRoute: typeof ApiPublicPublicationsRoute
  ApiPublicRecordRoute: typeof ApiPublicRecordRoute
  ApiPublicResearchRoute: typeof ApiPublicResearchRoute
  ApiPublicStatisticsRoute: typeof ApiPublicStatisticsRoute
  ApiRelatedRecordsRoute: typeof ApiRelatedRecordsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiAdminAccountsRoute: typeof ApiAdminAccountsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthSignUpRoute: typeof ApiAuthSignUpRoute
  ApiDashboardIpttoSummaryRoute: typeof ApiDashboardIpttoSummaryRoute
  ApiDashboardMeRoute: typeof ApiDashboardMeRoute
  ApiDashboardProfileRoute: typeof ApiDashboardProfileRoute
  ApiDashboardReportRoute: typeof ApiDashboardReportRoute
  ApiDashboardResearchReviewRoute: typeof ApiDashboardResearchReviewRoute
  ApiFilesConfirmUploadRoute: typeof ApiFilesConfirmUploadRoute
  ApiFilesSignedDownloadUrlRoute: typeof ApiFilesSignedDownloadUrlRoute
  ApiFilesSignedUploadUrlRoute: typeof ApiFilesSignedUploadUrlRoute
  ApiJobsFailedRoute: typeof ApiJobsFailedRoute
  ApiResearchApprovalTransitionsRoute: typeof ApiResearchApprovalTransitionsRoute
  ApiResearchSubmissionsRoute: typeof ApiResearchSubmissionsRouteWithChildren
  ApiAuthStaffPasswordResetCompleteRoute: typeof ApiAuthStaffPasswordResetCompleteRoute
  ApiAuthStaffPasswordResetRequestRoute: typeof ApiAuthStaffPasswordResetRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculties': {
      id: '/faculties'
      path: '/faculties'
      fullPath: '/faculties'
      preLoaderRoute: typeof FacultiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovations': {
      id: '/innovations'
      path: '/innovations'
      fullPath: '/innovations'
      preLoaderRoute: typeof InnovationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patents': {
      id: '/patents'
      path: '/patents'
      fullPath: '/patents'
      preLoaderRoute: typeof PatentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-areas': {
      id: '/research-areas'
      path: '/research-areas'
      fullPath: '/research-areas'
      preLoaderRoute: typeof ResearchAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/researchers': {
      id: '/researchers'
      path: '/researchers'
      fullPath: '/researchers'
      preLoaderRoute: typeof ResearchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commercialization': {
      id: '/api/commercialization'
      path: '/api/commercialization'
      fullPath: '/api/commercialization'
      preLoaderRoute: typeof ApiCommercializationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/innovations': {
      id: '/api/innovations'
      path: '/api/innovations'
      fullPath: '/api/innovations'
      preLoaderRoute: typeof ApiInnovationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organization-options': {
      id: '/api/organization-options'
      path: '/api/organization-options'
      fullPath: '/api/organization-options'
      preLoaderRoute: typeof ApiOrganizationOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patents': {
      id: '/api/patents'
      path: '/api/patents'
      fullPath: '/api/patents'
      preLoaderRoute: typeof ApiPatentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-publications': {
      id: '/api/public-publications'
      path: '/api/public-publications'
      fullPath: '/api/public-publications'
      preLoaderRoute: typeof ApiPublicPublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-record': {
      id: '/api/public-record'
      path: '/api/public-record'
      fullPath: '/api/public-record'
      preLoaderRoute: typeof ApiPublicRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-research': {
      id: '/api/public-research'
      path: '/api/public-research'
      fullPath: '/api/public-research'
      preLoaderRoute: typeof ApiPublicResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-statistics': {
      id: '/api/public-statistics'
      path: '/api/public-statistics'
      fullPath: '/api/public-statistics'
      preLoaderRoute: typeof ApiPublicStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/related-records': {
      id: '/api/related-records'
      path: '/api/related-records'
      fullPath: '/api/related-records'
      preLoaderRoute: typeof ApiRelatedRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/department-admin': {
      id: '/dashboard/department-admin'
      path: '/department-admin'
      fullPath: '/dashboard/department-admin'
      preLoaderRoute: typeof DashboardDepartmentAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/faculty-admin': {
      id: '/dashboard/faculty-admin'
      path: '/faculty-admin'
      fullPath: '/dashboard/faculty-admin'
      preLoaderRoute: typeof DashboardFacultyAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/iptto-officer': {
      id: '/dashboard/iptto-officer'
      path: '/iptto-officer'
      fullPath: '/dashboard/iptto-officer'
      preLoaderRoute: typeof DashboardIpttoOfficerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/lecturer': {
      id: '/dashboard/lecturer'
      path: '/lecturer'
      fullPath: '/dashboard/lecturer'
      preLoaderRoute: typeof DashboardLecturerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/super-admin': {
      id: '/dashboard/super-admin'
      path: '/super-admin'
      fullPath: '/dashboard/super-admin'
      preLoaderRoute: typeof DashboardSuperAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/departments/': {
      id: '/departments/'
      path: '/'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/departments/$departmentId': {
      id: '/departments/$departmentId'
      path: '/$departmentId'
      fullPath: '/departments/$departmentId'
      preLoaderRoute: typeof DepartmentsDepartmentIdRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/faculties/': {
      id: '/faculties/'
      path: '/'
      fullPath: '/faculties/'
      preLoaderRoute: typeof FacultiesIndexRouteImport
      parentRoute: typeof FacultiesRoute
    }
    '/faculties/$facultyId': {
      id: '/faculties/$facultyId'
      path: '/$facultyId'
      fullPath: '/faculties/$facultyId'
      preLoaderRoute: typeof FacultiesFacultyIdRouteImport
      parentRoute: typeof FacultiesRoute
    }
    '/innovations/': {
      id: '/innovations/'
      path: '/'
      fullPath: '/innovations/'
      preLoaderRoute: typeof InnovationsIndexRouteImport
      parentRoute: typeof InnovationsRoute
    }
    '/innovations/$innovationId': {
      id: '/innovations/$innovationId'
      path: '/$innovationId'
      fullPath: '/innovations/$innovationId'
      preLoaderRoute: typeof InnovationsInnovationIdRouteImport
      parentRoute: typeof InnovationsRoute
    }
    '/patents/': {
      id: '/patents/'
      path: '/'
      fullPath: '/patents/'
      preLoaderRoute: typeof PatentsIndexRouteImport
      parentRoute: typeof PatentsRoute
    }
    '/patents/$patentId': {
      id: '/patents/$patentId'
      path: '/$patentId'
      fullPath: '/patents/$patentId'
      preLoaderRoute: typeof PatentsPatentIdRouteImport
      parentRoute: typeof PatentsRoute
    }
    '/research/': {
      id: '/research/'
      path: '/'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/research/$recordId': {
      id: '/research/$recordId'
      path: '/$recordId'
      fullPath: '/research/$recordId'
      preLoaderRoute: typeof ResearchRecordIdRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/researchers/': {
      id: '/researchers/'
      path: '/'
      fullPath: '/researchers/'
      preLoaderRoute: typeof ResearchersIndexRouteImport
      parentRoute: typeof ResearchersRoute
    }
    '/researchers/$profileId': {
      id: '/researchers/$profileId'
      path: '/$profileId'
      fullPath: '/researchers/$profileId'
      preLoaderRoute: typeof ResearchersProfileIdRouteImport
      parentRoute: typeof ResearchersRoute
    }
    '/sign-up/iptto': {
      id: '/sign-up/iptto'
      path: '/iptto'
      fullPath: '/sign-up/iptto'
      preLoaderRoute: typeof SignUpIpttoRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-up/lecturer': {
      id: '/sign-up/lecturer'
      path: '/lecturer'
      fullPath: '/sign-up/lecturer'
      preLoaderRoute: typeof SignUpLecturerRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/api/admin/accounts': {
      id: '/api/admin/accounts'
      path: '/api/admin/accounts'
      fullPath: '/api/admin/accounts'
      preLoaderRoute: typeof ApiAdminAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-up': {
      id: '/api/auth/sign-up'
      path: '/api/auth/sign-up'
      fullPath: '/api/auth/sign-up'
      preLoaderRoute: typeof ApiAuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/iptto-summary': {
      id: '/api/dashboard/iptto-summary'
      path: '/api/dashboard/iptto-summary'
      fullPath: '/api/dashboard/iptto-summary'
      preLoaderRoute: typeof ApiDashboardIpttoSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/me': {
      id: '/api/dashboard/me'
      path: '/api/dashboard/me'
      fullPath: '/api/dashboard/me'
      preLoaderRoute: typeof ApiDashboardMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/profile': {
      id: '/api/dashboard/profile'
      path: '/api/dashboard/profile'
      fullPath: '/api/dashboard/profile'
      preLoaderRoute: typeof ApiDashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/report': {
      id: '/api/dashboard/report'
      path: '/api/dashboard/report'
      fullPath: '/api/dashboard/report'
      preLoaderRoute: typeof ApiDashboardReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/research-review': {
      id: '/api/dashboard/research-review'
      path: '/api/dashboard/research-review'
      fullPath: '/api/dashboard/research-review'
      preLoaderRoute: typeof ApiDashboardResearchReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/confirm-upload': {
      id: '/api/files/confirm-upload'
      path: '/api/files/confirm-upload'
      fullPath: '/api/files/confirm-upload'
      preLoaderRoute: typeof ApiFilesConfirmUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/signed-download-url': {
      id: '/api/files/signed-download-url'
      path: '/api/files/signed-download-url'
      fullPath: '/api/files/signed-download-url'
      preLoaderRoute: typeof ApiFilesSignedDownloadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/signed-upload-url': {
      id: '/api/files/signed-upload-url'
      path: '/api/files/signed-upload-url'
      fullPath: '/api/files/signed-upload-url'
      preLoaderRoute: typeof ApiFilesSignedUploadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/innovations/$innovationId': {
      id: '/api/innovations/$innovationId'
      path: '/$innovationId'
      fullPath: '/api/innovations/$innovationId'
      preLoaderRoute: typeof ApiInnovationsInnovationIdRouteImport
      parentRoute: typeof ApiInnovationsRoute
    }
    '/api/jobs/failed': {
      id: '/api/jobs/failed'
      path: '/api/jobs/failed'
      fullPath: '/api/jobs/failed'
      preLoaderRoute: typeof ApiJobsFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patents/$patentId': {
      id: '/api/patents/$patentId'
      path: '/$patentId'
      fullPath: '/api/patents/$patentId'
      preLoaderRoute: typeof ApiPatentsPatentIdRouteImport
      parentRoute: typeof ApiPatentsRoute
    }
    '/api/research/approval-transitions': {
      id: '/api/research/approval-transitions'
      path: '/api/research/approval-transitions'
      fullPath: '/api/research/approval-transitions'
      preLoaderRoute: typeof ApiResearchApprovalTransitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/submissions': {
      id: '/api/research/submissions'
      path: '/api/research/submissions'
      fullPath: '/api/research/submissions'
      preLoaderRoute: typeof ApiResearchSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/lecturer/profile': {
      id: '/dashboard/lecturer/profile'
      path: '/profile'
      fullPath: '/dashboard/lecturer/profile'
      preLoaderRoute: typeof DashboardLecturerProfileRouteImport
      parentRoute: typeof DashboardLecturerRoute
    }
    '/dashboard/lecturer/request-service': {
      id: '/dashboard/lecturer/request-service'
      path: '/request-service'
      fullPath: '/dashboard/lecturer/request-service'
      preLoaderRoute: typeof DashboardLecturerRequestServiceRouteImport
      parentRoute: typeof DashboardLecturerRoute
    }
    '/dashboard/lecturer/submit': {
      id: '/dashboard/lecturer/submit'
      path: '/submit'
      fullPath: '/dashboard/lecturer/submit'
      preLoaderRoute: typeof DashboardLecturerSubmitRouteImport
      parentRoute: typeof DashboardLecturerRoute
    }
    '/api/auth/staff-password-reset/complete': {
      id: '/api/auth/staff-password-reset/complete'
      path: '/api/auth/staff-password-reset/complete'
      fullPath: '/api/auth/staff-password-reset/complete'
      preLoaderRoute: typeof ApiAuthStaffPasswordResetCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/staff-password-reset/request': {
      id: '/api/auth/staff-password-reset/request'
      path: '/api/auth/staff-password-reset/request'
      fullPath: '/api/auth/staff-password-reset/request'
      preLoaderRoute: typeof ApiAuthStaffPasswordResetRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/innovations/$innovationId/archive': {
      id: '/api/innovations/$innovationId/archive'
      path: '/archive'
      fullPath: '/api/innovations/$innovationId/archive'
      preLoaderRoute: typeof ApiInnovationsInnovationIdArchiveRouteImport
      parentRoute: typeof ApiInnovationsInnovationIdRoute
    }
    '/api/innovations/$innovationId/publish': {
      id: '/api/innovations/$innovationId/publish'
      path: '/publish'
      fullPath: '/api/innovations/$innovationId/publish'
      preLoaderRoute: typeof ApiInnovationsInnovationIdPublishRouteImport
      parentRoute: typeof ApiInnovationsInnovationIdRoute
    }
    '/api/innovations/$innovationId/review': {
      id: '/api/innovations/$innovationId/review'
      path: '/review'
      fullPath: '/api/innovations/$innovationId/review'
      preLoaderRoute: typeof ApiInnovationsInnovationIdReviewRouteImport
      parentRoute: typeof ApiInnovationsInnovationIdRoute
    }
    '/api/research/submissions/$researchRecordId': {
      id: '/api/research/submissions/$researchRecordId'
      path: '/$researchRecordId'
      fullPath: '/api/research/submissions/$researchRecordId'
      preLoaderRoute: typeof ApiResearchSubmissionsResearchRecordIdRouteImport
      parentRoute: typeof ApiResearchSubmissionsRoute
    }
    '/dashboard/lecturer/edit/$researchRecordId': {
      id: '/dashboard/lecturer/edit/$researchRecordId'
      path: '/edit/$researchRecordId'
      fullPath: '/dashboard/lecturer/edit/$researchRecordId'
      preLoaderRoute: typeof DashboardLecturerEditResearchRecordIdRouteImport
      parentRoute: typeof DashboardLecturerRoute
    }
  }
}

interface DashboardLecturerRouteChildren {
  DashboardLecturerProfileRoute: typeof DashboardLecturerProfileRoute
  DashboardLecturerRequestServiceRoute: typeof DashboardLecturerRequestServiceRoute
  DashboardLecturerSubmitRoute: typeof DashboardLecturerSubmitRoute
  DashboardLecturerEditResearchRecordIdRoute: typeof DashboardLecturerEditResearchRecordIdRoute
}

const DashboardLecturerRouteChildren: DashboardLecturerRouteChildren = {
  DashboardLecturerProfileRoute: DashboardLecturerProfileRoute,
  DashboardLecturerRequestServiceRoute: DashboardLecturerRequestServiceRoute,
  DashboardLecturerSubmitRoute: DashboardLecturerSubmitRoute,
  DashboardLecturerEditResearchRecordIdRoute:
    DashboardLecturerEditResearchRecordIdRoute,
}

const DashboardLecturerRouteWithChildren =
  DashboardLecturerRoute._addFileChildren(DashboardLecturerRouteChildren)

interface DashboardRouteChildren {
  DashboardDepartmentAdminRoute: typeof DashboardDepartmentAdminRoute
  DashboardFacultyAdminRoute: typeof DashboardFacultyAdminRoute
  DashboardIpttoOfficerRoute: typeof DashboardIpttoOfficerRoute
  DashboardLecturerRoute: typeof DashboardLecturerRouteWithChildren
  DashboardSuperAdminRoute: typeof DashboardSuperAdminRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDepartmentAdminRoute: DashboardDepartmentAdminRoute,
  DashboardFacultyAdminRoute: DashboardFacultyAdminRoute,
  DashboardIpttoOfficerRoute: DashboardIpttoOfficerRoute,
  DashboardLecturerRoute: DashboardLecturerRouteWithChildren,
  DashboardSuperAdminRoute: DashboardSuperAdminRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DepartmentsRouteChildren {
  DepartmentsDepartmentIdRoute: typeof DepartmentsDepartmentIdRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
}

const DepartmentsRouteChildren: DepartmentsRouteChildren = {
  DepartmentsDepartmentIdRoute: DepartmentsDepartmentIdRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
}

const DepartmentsRouteWithChildren = DepartmentsRoute._addFileChildren(
  DepartmentsRouteChildren,
)

interface FacultiesRouteChildren {
  FacultiesFacultyIdRoute: typeof FacultiesFacultyIdRoute
  FacultiesIndexRoute: typeof FacultiesIndexRoute
}

const FacultiesRouteChildren: FacultiesRouteChildren = {
  FacultiesFacultyIdRoute: FacultiesFacultyIdRoute,
  FacultiesIndexRoute: FacultiesIndexRoute,
}

const FacultiesRouteWithChildren = FacultiesRoute._addFileChildren(
  FacultiesRouteChildren,
)

interface InnovationsRouteChildren {
  InnovationsInnovationIdRoute: typeof InnovationsInnovationIdRoute
  InnovationsIndexRoute: typeof InnovationsIndexRoute
}

const InnovationsRouteChildren: InnovationsRouteChildren = {
  InnovationsInnovationIdRoute: InnovationsInnovationIdRoute,
  InnovationsIndexRoute: InnovationsIndexRoute,
}

const InnovationsRouteWithChildren = InnovationsRoute._addFileChildren(
  InnovationsRouteChildren,
)

interface PatentsRouteChildren {
  PatentsPatentIdRoute: typeof PatentsPatentIdRoute
  PatentsIndexRoute: typeof PatentsIndexRoute
}

const PatentsRouteChildren: PatentsRouteChildren = {
  PatentsPatentIdRoute: PatentsPatentIdRoute,
  PatentsIndexRoute: PatentsIndexRoute,
}

const PatentsRouteWithChildren =
  PatentsRoute._addFileChildren(PatentsRouteChildren)

interface ResearchRouteChildren {
  ResearchRecordIdRoute: typeof ResearchRecordIdRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchRecordIdRoute: ResearchRecordIdRoute,
  ResearchIndexRoute: ResearchIndexRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

interface ResearchersRouteChildren {
  ResearchersProfileIdRoute: typeof ResearchersProfileIdRoute
  ResearchersIndexRoute: typeof ResearchersIndexRoute
}

const ResearchersRouteChildren: ResearchersRouteChildren = {
  ResearchersProfileIdRoute: ResearchersProfileIdRoute,
  ResearchersIndexRoute: ResearchersIndexRoute,
}

const ResearchersRouteWithChildren = ResearchersRoute._addFileChildren(
  ResearchersRouteChildren,
)

interface SignUpRouteChildren {
  SignUpIpttoRoute: typeof SignUpIpttoRoute
  SignUpLecturerRoute: typeof SignUpLecturerRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpIpttoRoute: SignUpIpttoRoute,
  SignUpLecturerRoute: SignUpLecturerRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

interface ApiInnovationsInnovationIdRouteChildren {
  ApiInnovationsInnovationIdArchiveRoute: typeof ApiInnovationsInnovationIdArchiveRoute
  ApiInnovationsInnovationIdPublishRoute: typeof ApiInnovationsInnovationIdPublishRoute
  ApiInnovationsInnovationIdReviewRoute: typeof ApiInnovationsInnovationIdReviewRoute
}

const ApiInnovationsInnovationIdRouteChildren: ApiInnovationsInnovationIdRouteChildren =
  {
    ApiInnovationsInnovationIdArchiveRoute:
      ApiInnovationsInnovationIdArchiveRoute,
    ApiInnovationsInnovationIdPublishRoute:
      ApiInnovationsInnovationIdPublishRoute,
    ApiInnovationsInnovationIdReviewRoute:
      ApiInnovationsInnovationIdReviewRoute,
  }

const ApiInnovationsInnovationIdRouteWithChildren =
  ApiInnovationsInnovationIdRoute._addFileChildren(
    ApiInnovationsInnovationIdRouteChildren,
  )

interface ApiInnovationsRouteChildren {
  ApiInnovationsInnovationIdRoute: typeof ApiInnovationsInnovationIdRouteWithChildren
}

const ApiInnovationsRouteChildren: ApiInnovationsRouteChildren = {
  ApiInnovationsInnovationIdRoute: ApiInnovationsInnovationIdRouteWithChildren,
}

const ApiInnovationsRouteWithChildren = ApiInnovationsRoute._addFileChildren(
  ApiInnovationsRouteChildren,
)

interface ApiPatentsRouteChildren {
  ApiPatentsPatentIdRoute: typeof ApiPatentsPatentIdRoute
}

const ApiPatentsRouteChildren: ApiPatentsRouteChildren = {
  ApiPatentsPatentIdRoute: ApiPatentsPatentIdRoute,
}

const ApiPatentsRouteWithChildren = ApiPatentsRoute._addFileChildren(
  ApiPatentsRouteChildren,
)

interface ApiResearchSubmissionsRouteChildren {
  ApiResearchSubmissionsResearchRecordIdRoute: typeof ApiResearchSubmissionsResearchRecordIdRoute
}

const ApiResearchSubmissionsRouteChildren: ApiResearchSubmissionsRouteChildren =
  {
    ApiResearchSubmissionsResearchRecordIdRoute:
      ApiResearchSubmissionsResearchRecordIdRoute,
  }

const ApiResearchSubmissionsRouteWithChildren =
  ApiResearchSubmissionsRoute._addFileChildren(
    ApiResearchSubmissionsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DepartmentsRoute: DepartmentsRouteWithChildren,
  FacultiesRoute: FacultiesRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InnovationsRoute: InnovationsRouteWithChildren,
  NewsRoute: NewsRoute,
  PatentsRoute: PatentsRouteWithChildren,
  PublicationsRoute: PublicationsRoute,
  ReportsRoute: ReportsRoute,
  ResearchRoute: ResearchRouteWithChildren,
  ResearchAreasRoute: ResearchAreasRoute,
  ResearchersRoute: ResearchersRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRouteWithChildren,
  ApiCommercializationRoute: ApiCommercializationRoute,
  ApiInnovationsRoute: ApiInnovationsRouteWithChildren,
  ApiOrganizationOptionsRoute: ApiOrganizationOptionsRoute,
  ApiPatentsRoute: ApiPatentsRouteWithChildren,
  ApiPublicPublicationsRoute: ApiPublicPublicationsRoute,
  ApiPublicRecordRoute: ApiPublicRecordRoute,
  ApiPublicResearchRoute: ApiPublicResearchRoute,
  ApiPublicStatisticsRoute: ApiPublicStatisticsRoute,
  ApiRelatedRecordsRoute: ApiRelatedRecordsRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiAdminAccountsRoute: ApiAdminAccountsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthSignUpRoute: ApiAuthSignUpRoute,
  ApiDashboardIpttoSummaryRoute: ApiDashboardIpttoSummaryRoute,
  ApiDashboardMeRoute: ApiDashboardMeRoute,
  ApiDashboardProfileRoute: ApiDashboardProfileRoute,
  ApiDashboardReportRoute: ApiDashboardReportRoute,
  ApiDashboardResearchReviewRoute: ApiDashboardResearchReviewRoute,
  ApiFilesConfirmUploadRoute: ApiFilesConfirmUploadRoute,
  ApiFilesSignedDownloadUrlRoute: ApiFilesSignedDownloadUrlRoute,
  ApiFilesSignedUploadUrlRoute: ApiFilesSignedUploadUrlRoute,
  ApiJobsFailedRoute: ApiJobsFailedRoute,
  ApiResearchApprovalTransitionsRoute: ApiResearchApprovalTransitionsRoute,
  ApiResearchSubmissionsRoute: ApiResearchSubmissionsRouteWithChildren,
  ApiAuthStaffPasswordResetCompleteRoute:
    ApiAuthStaffPasswordResetCompleteRoute,
  ApiAuthStaffPasswordResetRequestRoute: ApiAuthStaffPasswordResetRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
